name: Hello

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install libs       
        run: npx 
        
      - name: Test
        run: npm run test
